name: Test and Deploy

#on:
  #workflow_run:
    #workflows: [ "e2e-tests" ]
    #types: [ completed ]
    
#on:
  #pull_request:
    #branches: [ main ]
    
#on:
  #release:
    #types: [ published ]
    
#on: [ workflow_dispatch ]

on:
  push:
    branches: [ main ]


jobs:

  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install-command: npm install --legacy-peer-deps
          #build: npm run build --legacy-peer-deps
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CI: ""

  deploy:
    needs: cypress
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Build the frontend image
      run: docker build . --file ./Dockerfile.prod --tag username/image:$(date +%s) --tag username/image:latest
      
    - name: Docker Push frontend
      run: docker push username/image --all-tags
