version: "3.9"
services:
  si:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    image: IMAGE_NAME
    container_name: siprojekat_frontend
    ports:
      - "3000:3000"
    restart: on-failure:10
