version: "3.9"
services:
  si:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    image: IMAGE_NAME
    container_name: siprojekat_frontend
    ports:
      - "80:80"
    restart: on-failure:10
